In [190]:
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [191]:
df=pd.read_csv('bihar_election_dataset.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'bihar_election_dataset.csv'

In [ ]:
df.head()

,Name,Age_Group,Gender,Geography,Education,Occupation,Caste,Voted_Party
0,Rekha Ansari,50-59,Female,Rural,Upto 9th,Labour,SC,MGB
1,Priyanka Paswan,30-39,Female,Rural,10th Pass,Skilled Professional,General,MGB
2,Abdul Choudhary,60-69,Male,Rural,Post-Graduate,Skilled Professional,Muslim,MGB
3,Deepak Ansari,40-49,Male,Rural,Upto 9th,Skilled Professional,OBC,NDA
4,Manju Choudhary,20-29,Female,Rural,Upto 9th,Farmer,OBC,Others

In [ ]:
df.shape

(20000, 8)

In [ ]:

df.duplicated().value_counts()

False    19650
True       350
Name: count, dtype: int64

In [ ]:
df=df.drop_duplicates()

In [ ]:
df=df.drop('Name',axis=1)

In [ ]:
df['Education'].value_counts()
df.sample(5)

,Age_Group,Gender,Geography,Education,Occupation,Caste,Voted_Party
5883,60-69,Male,Rural,Graduate,Farmer,EBC,NDA
19347,30-39,Female,Rural,Graduate,Farmer,EBC,NDA
12425,40-49,Female,Rural,Not Gone to School,Labour,General,NDA
8163,40-49,Male,Rural,12th Pass,Skilled Professional,Yadav,MGB
3401,30-39,Female,Rural,Not Gone to School,Skilled Professional,Muslim,MGB

In [ ]:

df['Age_Group'].value_counts()

Age_Group
30-39         4973
20-29         4337
40-49         4139
50-59         2879
60-69         1760
70 & Above    1164
18-19          398
Name: count, dtype: int64

In [ ]:
df['Caste'].value_counts()

Caste
EBC        4392
General    3489
Muslim     3274
SC         3006
Yadav      2747
OBC        2563
ST          179
Name: count, dtype: int64

In [ ]:
df['Voted_Party'].value_counts()

Voted_Party
NDA       8386
MGB       8139
Others    2382
JSP        743
Name: count, dtype: int64

In [ ]:
df.sample(5)

,Age_Group,Gender,Geography,Education,Occupation,Caste,Voted_Party
10231,30-39,Male,Rural,Upto 9th,Housewife,General,JSP
3481,30-39,Male,Rural,12th Pass,Skilled Professional,OBC,NDA
19972,20-29,Female,Rural,Upto 9th,Unemployed,Yadav,MGB
11048,60-69,Female,Urban,12th Pass,Labour,Yadav,MGB
13998,30-39,Male,Rural,Post-Graduate,Unemployed,Muslim,MGB

In [ ]:
import pandas as pd
education_ord = [
    'Not Gone to School', 
    'Upto 9th', 
    '10th Pass', 
    '12th Pass', 
    'Graduate', 
    'Post-Graduate', 
    'Professional Education'
]
age_ord = [
    '18-19', 
    '20-29', 
    '30-39', 
    '40-49', 
    '50-59', 
    '60-69', 
    '70 & Above'
]
transformer = ColumnTransformer(transformers=[
    ('ord', OrdinalEncoder(categories=[education_ord, age_ord]), ['Education', 'Age_Group']),
    ('nom', OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'), 
     ['Gender', 'Geography', 'Occupation', 'Caste'])
], remainder='passthrough')

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:

X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Voted_Party']),df['Voted_Party'],test_size=0.25)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
lr_pipe = Pipeline([
    ('preprocessing', transformer),
    ('scaler', StandardScaler(with_mean=False)),
    ('model', LogisticRegression(
        solver='lbfgs',
        max_iter=1000,
        random_state=42
    ))
])
lr_pipe.fit(X_train, y_train)
y_pred_lr = lr_pipe.predict(X_test)
print(f" Accuracy: {accuracy_score(y_test, y_pred_lr):.2f}")

 Accuracy: 0.66